main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 2
  - identifier: about
    name: About
    url: /about/
    weight: 3
#  - identifier: archive
#    name: Archive
#    url: /archive/
#    weight: 3
  - name: Projects
    identifier: projects
    weight: 4
    url: /projects/
