main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 20
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 20
  - identifier: about
    name: About
    url: /about/
    weight: 30
#  - identifier: archive
#    name: Archive
#    url: /archive/
#    weight: 3
  - name: Projects
    identifier: projects
    weight: 40
    url: /projects/
