name: Delete Test Site

on:
  delete:
     branches-ignore:
       - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
 
  check:
    runs-on: ubuntu-latest # ubuntu-latest
    outputs:
      branch: ${{ steps.branch-name.outputs.current_branch }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.5

      - run: echo Running on branch ${{ steps.branch-name.outputs.current_branch }}

  clear:
    runs-on: ubuntu-latest
    needs: check
    # Clean to the development environment
    environment:
      name: development

    steps:

      - name: Clean up
        run: |
          echo "Clean up for branch ${{ needs.check.outputs.branch }}"

      - name: Remove old test site
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ vars.ftp_server }}
          user: ${{ vars.ftp_username }}
          password: ${{ secrets.ftp_password }}
          remoteFiles: ''
          remoteDirectories: "${{ needs.check.outputs.branch }}/"
          workingDir: "/"
          ignoreSSL: "1"